from project import *
from shared import *

if __name__ == "__main__":
    p = "GTACGTGGTGCTGGGGCAGTTGCTTTAGCGCGAGAG"
    gene = "ACAAGTACGTGGTGCTGGGCTATAAAAACAAATGGAACTGCGCTGCAGTTGCTTTAGTTGACAGAATTCTCGACGCAGTCACAGCAAAAAACCGAAGGCGGCTAGAAATCAACAACTTTCCAGTTCGAGTGTTTCTAAATTCTGGTTATCCCGTTGAGCAAATATCCTAAATTTTAAGCAAAATGGCTGGACGCGATGCGGCTTCCAATCAGTTGATTGACTACAAAAACTCCCAAACGGTGAGTGTGTTGGTGTGCGAGCGCGAGAGAGCGCAACTGCATGTGTGTGCGTGTGTGTGCCGGCAGGAAAATAAGAAAACAAGAAAGGCAAAAAAGACAAAAAGAGAAGGGAGAAGCATTGTACGAAATGAAATAAACAAAAAACAAGACAATTTCAGTAACGATTGCTATGAGCCTGTACTTTCCATTAATTCCATTAATTATTAAAATGCGAAAAACAACAAAGGCTTGTCCAACAAATGCCAGTAATG$"
    A = get_suffix_array(gene)
    L = get_bwt(gene, A)
    F = get_F(L)
    M = get_M(F)
    occ = get_occ(L)
    m = exact_suffix_matches(p, M, occ)
    print(m)
    print(A[m[0][1]])

    reads = [p]
    align = align_genome(reads, gene, 2, 200)
    print(align)

